-- MDEP-12: execute manually after replacing angle-bracket placeholders.
-- Silver remains externally managed by Spark/Flink; this script creates only
-- Snowflake access objects and the Snowflake-native Gold destination.
USE ROLE <MDEP_ADMIN_ROLE>;

CREATE WAREHOUSE IF NOT EXISTS MDEP_TRANSFORM_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE DATABASE IF NOT EXISTS MDEP;
CREATE SCHEMA IF NOT EXISTS MDEP.SILVER_EXT;
CREATE SCHEMA IF NOT EXISTS MDEP.GOLD;

CREATE OR REPLACE EXTERNAL VOLUME MDEP_ICEBERG_VOLUME
  STORAGE_LOCATIONS = ((NAME = 'mdep_iceberg'
    STORAGE_PROVIDER = 'S3'
    STORAGE_BASE_URL = 's3://<MDEP_ICEBERG_BUCKET>/iceberg/'
    STORAGE_AWS_ROLE_ARN = '<MDEP_SNOWFLAKE_S3_ROLE_ARN>'));

CREATE OR REPLACE CATALOG INTEGRATION MDEP_ICEBERG_OBJECT_STORE
  CATALOG_SOURCE = OBJECT_STORE TABLE_FORMAT = ICEBERG ENABLED = TRUE;

-- Run DESC EXTERNAL VOLUME MDEP_ICEBERG_VOLUME and grant the returned Snowflake
-- IAM user/external ID read access to the bucket before creating these tables.
CREATE OR REPLACE ICEBERG TABLE MDEP.SILVER_EXT.REF_EXCHANGE_RATES
  EXTERNAL_VOLUME = 'MDEP_ICEBERG_VOLUME' CATALOG = 'MDEP_ICEBERG_OBJECT_STORE'
  METADATA_FILE_PATH = '<silver/ref_exchange_rates/metadata/vN.metadata.json>';
CREATE OR REPLACE ICEBERG TABLE MDEP.SILVER_EXT.REF_LOCATIONS
  EXTERNAL_VOLUME = 'MDEP_ICEBERG_VOLUME' CATALOG = 'MDEP_ICEBERG_OBJECT_STORE'
  METADATA_FILE_PATH = '<silver/ref_locations/metadata/vN.metadata.json>';
CREATE OR REPLACE ICEBERG TABLE MDEP.SILVER_EXT.CORE_CUSTOMERS
  EXTERNAL_VOLUME = 'MDEP_ICEBERG_VOLUME' CATALOG = 'MDEP_ICEBERG_OBJECT_STORE'
  METADATA_FILE_PATH = '<silver/core_customers/metadata/vN.metadata.json>';
CREATE OR REPLACE ICEBERG TABLE MDEP.SILVER_EXT.CORE_PRODUCTS
  EXTERNAL_VOLUME = 'MDEP_ICEBERG_VOLUME' CATALOG = 'MDEP_ICEBERG_OBJECT_STORE'
  METADATA_FILE_PATH = '<silver/core_products/metadata/vN.metadata.json>';
CREATE OR REPLACE ICEBERG TABLE MDEP.SILVER_EXT.CORE_ORDERS
  EXTERNAL_VOLUME = 'MDEP_ICEBERG_VOLUME' CATALOG = 'MDEP_ICEBERG_OBJECT_STORE'
  METADATA_FILE_PATH = '<silver/core_orders/metadata/vN.metadata.json>';
CREATE OR REPLACE ICEBERG TABLE MDEP.SILVER_EXT.CORE_PAYMENTS
  EXTERNAL_VOLUME = 'MDEP_ICEBERG_VOLUME' CATALOG = 'MDEP_ICEBERG_OBJECT_STORE'
  METADATA_FILE_PATH = '<silver/core_payments/metadata/vN.metadata.json>';

CREATE ROLE IF NOT EXISTS MDEP_TRANSFORMER;
GRANT USAGE ON WAREHOUSE MDEP_TRANSFORM_WH TO ROLE MDEP_TRANSFORMER;
GRANT USAGE ON DATABASE MDEP TO ROLE MDEP_TRANSFORMER;
GRANT USAGE ON SCHEMA MDEP.SILVER_EXT TO ROLE MDEP_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA MDEP.SILVER_EXT TO ROLE MDEP_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA MDEP.GOLD TO ROLE MDEP_TRANSFORMER;
